config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]

  resources :items, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :bookings, only: [:index, :new, :create, :edit, :update, :destroy] do
    member do
      patch :set_close
      patch :set_open
    end
  end

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'pages/booking', path: '/my-bookings'

end

app/models/booking.rb
class Booking < ActiveRecord::Base

  belongs_to :user
  belongs_to :item

  after_create :subtract_quantity

  validates_presence_of :item_id, :quantity, :start_date, :end_date, :status
  validate :available_quantity

  enum status: { open: 0, closed: 1, expired: 2 }

  after_initialize :set_default_status, :if => :new_record?

  def set_default_status
    self.status ||= 0
  end

  def subtract_quantity
    new_quantity = self.item.quantity - self.quantity
    self.item.update_attributes(:quantity => new_quantity)
  end

  def available_quantity
    if self.quantity > self.item.quantity && self.item.quantity != 0
      errors.add(:quantity, "You can't book more than #{self.item.quantity}")
    elsif self.item.quantity == 0
      errors.add(:quantity, "Sorry! #{self.item.name} is currently out of stock")
    end
  end

  def overdue
    if self.end_date < Time.now && !self.is_closed?
      self.update(status: 2)
    elsif self.end_date > Time.now && !self.is_closed?
      self.update(status: 0)
    end
  end

  def is_overdue?
    due_date_absolute < Time.now && self.is_expired?
  end

  def due_date_absolute
    self.end_date
  end

  def overdue_rate
    10
  end

  def fine
    overdue_rate * ((Time.now.beginning_of_day - due_date_absolute) / 1.days)
  end

end

app/models/item.rb
class Item < ActiveRecord::Base

  enum status: { not_available: 0, available: 1 }

  validates_presence_of :name, :quantity, :status

  after_create :random_product_code

  has_many :bookings

  scope :available, -> { where(status: 1) }

  def returnable?
    self.returnable == true
  end

  def random_product_code
    random = ['1'..'9'].map { |i| i.to_a }.flatten
    product_code = (0...7).map { random[rand(random.length)] }.join
    self.update_attributes(:code => product_code)
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  validates_uniqueness_of :email

  enum status: { active: 0, suspended: 1}

  after_initialize :set_default, :if => :new_record?

  has_many :bookings

  def set_default
    self.admin ||= false
    self.status ||= "Active"
  end

  def check_status
    self.bookings.pluck(:status).include?(2) ? self.update(status: 1) : self.update(status: 0)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to root_path, alert: "You must be logged in to access this page" if current_user.nil?
  end

  def require_admin
    unless current_user && current_user.admin?
      redirect_to root_path, alert: "You are not authorised to access this page"
    end
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :require_user, only: [:new]
  before_action :set_booking, only: [:set_open, :set_close, :update]
  before_action :require_admin, only: [:index, :set_open, :set_close, :update]

  def index
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = current_user.bookings.new(booking_params)
    if @booking.save
      redirect_to root_path, notice: 'Your booking has been sucessfully submitted'
    else
      flash[:alert] = 'Opps, thas was embarrassing. Try again?'
      render 'new'
    end
  end

  def set_open
    adjust_quantity = @booking.item.quantity - @booking.quantity
    @booking.update_attributes(status: 0)
    @booking.item.update_attributes(:quantity => adjust_quantity)
    redirect_to bookings_path
  end

  def set_close
    @booking.update_attributes(status: 1)
    adjust_quantity = @booking.quantity + @booking.item.quantity
    if @booking.item.returnable?
      @booking.item.update_attributes(:quantity => adjust_quantity)
    end
    redirect_to bookings_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:item_id, :quantity, :start_date, :end_date)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_filter :set_item, only: [:show, :edit, :update, :destroy]
  before_action :require_admin

  def index
    @items = Item.all
  end

  def new
    @item ||= Item.new
    render
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path, notice: "#{@item.name} was successfully created"
    else
      flash[:alert] = 'Something went wrong, try again?'
      render 'new'
    end
  end

  def show
  end

  def edit
    if @item
      render
    else
      redirect_to items_path, alert: 'Item not found'
    end
  end

  def update
    if @item.update_attributes(item_params)
      flash[:notice] = "The #{@item.name} was successfully updated."
      redirect_to items_path
    else
      render 'edit'
      flash[:alert] = 'Something went wrong, try again?'
    end
  end

  def destroy
    if @item.destroy!
      redirect_to items_path, flash[:notice] = "Item destroyed."
    else
      redirect_to items_path, flash[:alert] = "Item delete failed."
    end
  end

  private
  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :code, :quantity, :returnable, :status)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_action :require_user, only: [:booking]

  def index
    if current_user
      @user_bookings = current_user.bookings
    end
  end

  def booking
    @user_bookings = current_user.bookings
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "You're logged in"
    else
      flash.now.alert = "Email or password is invalid"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "You're logged out"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_alert.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible alert-miss" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible alert-miss" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  </div>
<% end %>

app/views/bookings/index.html.erb
<div class="container">
  <h3>Bookings List</h3>
  <table class="table table-responsive table-striped table-hover">
    <thead>
      <tr>
        <th>Booking ID</th>
        <th>Item Name</th>
        <th>Quantity</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Status</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.id %></td>
        <td><%= booking.item.name %></td>
        <td><%= booking.quantity %></td>
        <td><%= booking.start_date.strftime("%B %d, %Y") %></td>
        <td><%= booking.end_date.strftime("%B %d, %Y") %></td>
        <td><%= booking.status %></td>
        <td>
          <% if booking.closed? %>
            <%= link_to 'Open',set_open_booking_path(booking), method: :patch, class: "btn btn-success btn-xs" %>
          <% else %>
            <%= link_to 'Close',set_close_booking_path(booking), method: :patch, class: "btn btn-danger btn-xs" %>
          <% end %>
        </td>
      <tr>
      <% end %>
    </tbody>
  </table>

</div><!-- /.container -->

app/views/bookings/new.html.erb
<div class="container">
  <%= bootstrap_form_for(@booking) do |f| %>
    <%= f.collection_select :item_id, Item.available.order(:name), :id, :name, {} %>
    <%= f.text_field :start_date, value: "#{Time.zone.now.strftime("%d %B %Y at %I:%M %p")}", readonly: true %> 
    <%= f.text_field :end_date, value: "#{2.days.from_now.beginning_of_day.strftime("%d %B %Y at %I:%M %p")}", readonly: true %>
    <%= f.text_field :quantity, placeholder: "1" %>
    <%= f.submit 'Submit', class: 'btn btn-success' %>
    <%= link_to "Cancel", bookings_path, class: 'btn btn-default' %>
  <% end %>
</div>

app/views/items/_item_form.html.erb
<div class="container">
  <%= bootstrap_form_for [@item] do |f| %>
    <%= f.label :name %> <%= f.text_field :name, hide_label: true %>
    <%= f.select(:status, Item.statuses.keys.map {|status| [status.titleize,status]}, {}) %>
    <%= f.text_field :quantity, placeholder: "10" %>
    <%= f.check_box :returnable %>
    <%= f.submit 'Submit'%>
    <%= link_to '<i class="fa fa-undo"></i> Cancel'.html_safe, items_path, class: "btn btn-default" %>
  <% end %>
</div>

app/views/items/edit.html.erb
<div class="container">
  <h3>Edit <%= @item.name %></h3>
  <%= render "item_form" %>
</div>

app/views/items/index.html.erb
<div class="container">
  <h3>Items
  <%= link_to "New Item", new_item_path, class: 'btn btn-primary' %></h3>
  <table class="table table-responsive table-striped table-hover" class="display">
    <thead>
      <tr>
        <th>Code</th>
        <th>Item</th>
        <th>Quantity</th>
        <th>Status</th>
        <th>Returnable?</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% if @items.any? %>
        <% @items.each do |item| %>
        <tr>
          <td><%= item.code %></td>
          <td><%= item.name %></td>
          <td><%= item.quantity %></td>
          <td><%= item.status.humanize %></td>
          <td><%= item.returnable %></td>
          <td><%= link_to '<i class="fa fa-pencil"></i> Edit'.html_safe, edit_item_path(item), class: 'btn btn-warning btn-xs' %>
            <%= link_to '<i class="fa fa-trash-o"></i> Delete'.html_safe, item_path(item), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger btn-xs' %>
          </td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/items/new.html.erb
<div class="container">
  <h3>New Item</h3>
  <%= render "item_form" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookie</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <!-- Bootstrap core CSS -->
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  </head>

  <%= render partial: 'alert' %>

  <div class="container header clearfix">
    <nav>
      <ul class="nav nav-pills pull-right">
        <li role="presentation"> <%= link_to '<i class="fa fa-home"></i> Home'.html_safe, root_path %> </li>
        <li role="presentation"> <%= link_to '<i class="fa fa-th"></i> New Booking'.html_safe, new_booking_path %> </li>
        <li role="presentation"> <%= link_to '<i class="fa fa-check-square-o"></i> My Bookings'.html_safe, pages_booking_path %> </li>
      </ul>
    </nav>
    <h3 class="text-muted"><%= link_to "Bookie", root_path %></h3>
  </div>

  <body>
    <%= yield %>
  </body>

  <div class="container">
    <footer class="footer pull-right">
      <p>
        <% if current_user && current_user.admin? %>
          [ <%= link_to '<i class="fa fa-folder-open"></i> Items'.html_safe, items_path %> ]
          [ <%= link_to '<i class="fa fa-shopping-cart"></i> Bookings'.html_safe, bookings_path %> ]
        <% end %>
        &copy; Bookie 2015
      </p>
    </footer>
  </div>
</html>

app/views/pages/_booking.html.erb
<table class="table table-bordered table-responsive">
  <thead>
    <tr>
      <th>Booking ID</th>
      <th>Item Name</th>
      <th>Quantity</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Status</th>
      <th>Fine</th>
    </tr>
  </thead>
  <tbody>
    <% @user_bookings.each do |u_booking| %>
    <tr>
      <td><%= u_booking.id %></td>
      <td><%= u_booking.item.name %></td>
      <td><%= u_booking.quantity %></td>
      <td><%= u_booking.start_date.strftime("%B %d, %Y") %></td>
      <td><%= u_booking.end_date.strftime("%B %d, %Y") %></td>
      <td><%= u_booking.status %></td>
      <td>
        <% if u_booking.is_overdue? == true %>
          <%= number_to_currency(u_booking.fine) %>
        <% else %>
          N/A
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/pages/booking.html.erb
<div class="container">
  <h3>My Bookings</h3>
  <table class="table table-bordered table-responsive">
    <thead>
      <tr>
        <th>Booking ID</th>
        <th>Item Name</th>
        <th>Quantity</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Status</th>
        <th>Fine</th>
      </tr>
    </thead>
    <tbody>
      <% @user_bookings.each do |u_booking| %>
      <tr>
        <td><%= u_booking.id %></td>
        <td><%= u_booking.item.name %></td>
        <td><%= u_booking.quantity %></td>
        <td><%= u_booking.start_date.strftime("%B %d, %Y") %></td>
        <td><%= u_booking.end_date.strftime("%B %d, %Y") %></td>
        <td><%= u_booking.status %></td>
        <td>
          <% if u_booking.is_overdue? == true %>
            <%= number_to_currency(u_booking.fine) %>
          <% else %>
            N/A
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/pages/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Bookie</h1>
    <p class="lead">Welcome to Bookie 0.1</p>
    <% if current_user %>
      <p class="label label-info">
        You're logged in as <%= current_user.email %>.
        <%= link_to "Log Out?", logout_path %>
      </p>
    <% else %>
      <%= link_to "Sign Up", signup_path, class: 'btn btn-success btn-lg' %>
      <%= link_to "Sign In", login_path, class: 'btn btn-primary btn-lg' %>
    <% end %>
  </div>

  <div class="row marketing">
    <div class="col-lg-12">
    <% if current_user %>
      <h4> My Bookings </h4>
      <p> <%= render "booking" %> </p>
    <% end %>
    </div>
  </div>
</div> <!-- /container -->

app/views/users/new.html.erb
<div class="container">
  <h3>Sign Up</h3>

  <%= bootstrap_form_for @user do |f| %>
    <%= f.text_field :email %>
    <%= f.password_field :password %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit "Sign Up" %>
    <%= link_to "Cancel", root_path, class: 'btn btn-default' %>
  <% end %>
</div>